package com.example.demo;



import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

@RestController // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private EmployeeRepository employeeRepository;

  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody String addNewEmployee (@RequestParam String name
      , @RequestParam int age ,@RequestParam int id) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    Employee n = new Employee();
    n.setName(name);
    n.setAge(age);
    n.setId(id);
    employeeRepository.save(n);
    return "Saved";
  }
  
  @GetMapping(path="/test")
  public String getTest() {
    // This returns a JSON or XML with the users
    //return userRepository.findAll();
	  return "Hello";
  }
  
  @GetMapping(path="/all")
  public @ResponseBody Iterable<Employee> getAllUsers() {
    // This returns a JSON or XML with the users
    return employeeRepository.findAll();
	  
  }
}
